name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml

concurrency:
  group: ${{ github.ref_name }}-dockerhub
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dockerHubDescription:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.fork == false }}
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Modify readme for DockerHub
        run: |
          sed -i '3,4d' README.md

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@dc67fad7001ef9e8e3c124cb7a64e16d0a63d864 # v3.4.2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: nginx/nginx-ingress
          short-description: ${{ github.event.repository.description }}
