[tool.black]
line-length = 120
target-version = ['py310']
extend-exclude = '.*pb2.*'

[tool.isort]
atomic = true
profile = "black"
line_length = 120
skip_gitignore = true
balanced_wrapping = true
filter_files = true
skip_glob = ['*pb2*']

[tool.pytest.ini_options]
pythonpath = [
    ".",
    "tests/suite",
    "tests/suite/grpc",
    "tests/suite/fixtures",
    "tests/suite/utils",
]
addopts = "--tb=native -ra --disable-warnings -x -l --profile -v"
log_cli = true
markers =[
    "appprotect",
    "dos",
    "ingresses",
    "policies",
    "rewrite",
    "skip_for_nginx_oss",
    "smoke",
    "ts",
    "vs",
    "vsr",
]
testpaths = [
    "tests",
    "perf-tests",
]
